### ISSUE TITLE
Request: Place Bubo jars on a Maven-compliant repo somewhere

### ISSUE THREAD

**Issue by dljsjr** [lessthanoptimal/Bubo#1]
Hey there,

I was just wondering if there were ever any plans to place Bubo on a Maven-compliant service like Bintray or Maven Central. We use it quite a bit and we're trying to clean up our rather disgusting build infrastructure; currently we vendor Bubo and self-host the .jars but we'd love to be able to pull upstream stable releases without needing to host the jars on an internal Maven repository and do a manual build when we want to update to newer versions of Bubo.

**Comment by lessthanoptimal** [comment]
Hey Doug,

Guess you forgot that this is one of my projects.  Right now I have no plans to put it on Maven Central but that's just because I'm not actively using it and hardly anyone knows about it.  One issue is that it depends on jMonkeyEngine, which isn't on Maven Central (as of two years ago), but that's only used for visualization.  I think I designed it so that it can still compile without JMonkeyEngine.
- Peter

**Comment by dljsjr** [comment]
Haha I didn't forget, I just didn't wanna be overly friendly out of the gate.

It's true that JME is not on Maven Central but they do have a self-hosted Maven repo, we're working on migrating our vendored version of JME over to their Maven repo as we speak.

We're basically trying to stop our open-source code (https://github.com/ihmcrobotics/ihmc-open-robotics-software) from having to resolve .jars that live on the IHMC Nexus instance and without needing to put binaries (e.g. vendored jars) in git. Just thought I'd ask. Feel free to close this if you want, since Bubo is open source and permissibly licensed we may just push our vendored version up to our public Bintray maven repo.

**Comment by dljsjr** [comment]
Actually RE: vendoring; I assumed Bubo was Apache 2.0 because all of the rest of your stuff is but I see now that it has an empty LICENSE file. What is the license for Bubo?

**Comment by lessthanoptimal** [comment]
Dear Sir/Madam,

Thank you for bringing these issues to our attention.  The license of Bubo is Apache 2.0 and the empty file will be fixed in due course.  Feel free to, as you say, "push our vendored version" to Bintray.  When active development is resumed a Maven Central version will be made available.
- Project Bubo Development Team

**Comment by dljsjr** [comment]
😂

Thanks Peter! Hope all is well!
